### ISSUE TITLE
Full stack harjoitustyön katselmointi

### ISSUE THREAD

**Issue by outisa** [matiasjokela/exam_prep_app_backend#1]
Hei @matiasjokela!

Katselmoin Full stack kurssin harjoitustyösi. Oikein hienoa työtä!

Kuten jo aikaisemmassa viestittelyssämme keksusteltiin, niin koodisi on järkevästi organisoitu. Front endin puolella näkymäkomponenteissa on jonkin verran toisteisuutta, mutta kuten totesitkin, tähän voi kiinnittää huomiota tulevissa projekteissa.

Admin komponentti oli hyvä lisäys ja näyttäisi siltä, että harjoitustyösi olisi helposti jatkokehitettävissä.

Käyttöliittymä on selkeä ja uusien kysymysten lisääminen on helppoa.

Koodamisen iloa!

**Comment by matiasjokela** [comment]
Hei.

Kiitos työn katselmoinnista! Palautteesi oli osuvaa ja rakentavaa ja sen avulla minun on helppo välttää kyseisiä virheitä jatkossa, joten kiitos erityisesti siitä, että näit vaivaa sen antamiseen!
